# Generated by Django 5.2.10 on 2026-01-20 18:09

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aceite_cadastro',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[users.validators.validate_cpf]),
        ),
    ]
