# Generated by Django 5.2.10 on 2026-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_aceite_cadastro_alter_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
