# Generated by Django 5.2.10 on 2026-01-21 14:49

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, validators=[users.validators.validade_nascimento]),
        ),
    ]
