# Generated by Django 5.2.10 on 2026-01-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subitem',
            old_name='projects',
            new_name='project',
        ),
    ]
